nbd-wtf/go-nostr

event/event.go

This did not migrate over from the [original](https://github.com/fiatjaf/nostr-relay-poc/commit/6c6bf45c72aefafcd9f0fa85ae3baddca543e486) relay code

Not returning tags

---

event/event.go

[original fix](https://github.com/fiatjaf/nostr-relay-poc/commit/a1aaed41c6b1f9e422f6f0413ee18f351efdb31d)

HTML fix did not port

---

example/example.go

Fixed a typo and capitalised example

---

README.md
example/example.go
relaypool.go

Not sure if you will like it or not but this is the simplest way I could see to fix the issue.

problem: can't unsub

---

nip04/nip04.go

As discussed in #21
Remove extra padding in nip04

fix: nip04 remove extra padding

---

event_test.go
relay_test.go
relaypool_test.go

was trying to reproduce the issue described in https://github.com/nbd-wtf/go-nostr/issues/23
no success in reproducing that specific problem, but i believe the test can still be useful to help in avoiding regression bugs in the future.

relaypool: add a unique events subscription smoke test

---

README.md
example/example.go

working example of subscription and publication

added example/example.go with subscription and publication code example

---

README.md
example/example.go
relay.go
subscription.go

related to #36 #35
data races were detected when sub.Unsub() was called in the middle of a subscription (detected by running test scripts with -race flag).

added sub.mutex handling in the relay Connect() function

---

README.md
example/example.go
nip42/nip42.go
relay.go
subscription.go

Plus a README.md update and one builder function to nip42.go

Added some NIP-42 functionality to the client (relay.go)

---

event.go
event_aux.go
helpers.go
relay.go
tags.go

moved escapeString into helpers.go and changed the MarshalJSON method for event to use the correct string escaping

event marshal JSON

---

nip11/fetch.go
normalize.go

wanted to fetch some info docs for relays that I liked

added function to fetch NIP-11 documents

---

relay.go

Fix execution sequence

---

README.md

Added Github Actions status badge to readme.

docs: add ci status in readme

---

nip05/nip05.go

feat: add check redirect for identifier request

---

example/example.go
filter_aux.go
filter_test.go

String() always append quotes. use StringBytes() instead.

use StringBytes() instead of String()

---

example/example.go

revert accidentally changes

---

event_test.go

fix event comparison in EventSerialization test

---

README.md

I found some build errors in the README code example.
This PR fixes the build errors.

fix README code example

---

metadata.go

Add fields usually needed by a client to show the profile

Add fields to ProfileMetadata

---

nip11/types.go

https://github.com/nostr-protocol/nips/pull/592

add icon to RelayInformationDocument

---

Makefile
envelopes.go
event.go
log_normal.go
nip05/nip05.go
nip11/fetch.go
nip19/nip19.go
nip26/nip26.go
nip26/nip26_test.go
nip42/nip42.go
nson/nson.go
nson/nson_test.go
relay.go
sdk/input.go
sdk/references.go
subscription.go
tags.go

hello, I refactored the code with effective go rules and also resolved some warns, there are some structs that are used in `json unmarshal or marshal` functions but without json tags! also, I fixed them.

style: using effective go and refactoring

---

relay.go

This and [this](https://github.com/gobwas/ws/pull/190) will fix race conditions in go-nostr.

fix race condition in Close

---

.github/workflows/test.yml

fix GitHub workflow

---

nip52/calendar_event.go

Add timezones to CalendarEvent

---

utils.go
utils_test.go

fix IsValidRelayURL

---

nson/README.md
nson/nson_test.go

Based on https://100go.co/89-benchmarks/ guide, we have to take some action to get an accurate benchmark. I updated these benchmarks to have a better result.

Fix nson benchmarks

---

count_test.go
envelopes_test.go
eose_test.go
event_test.go
filter_test.go
go.mod
go.sum
nip05/nip05_test.go
nip11/nip11_test.go
nip13/deprecated.go
nip19/nip19_test.go
nip29/nip29_test.go
nip44/nip44_test.go
nip46/nip46_test.go
nip49/nip49_test.go
nip96/nip96_test.go
normalize_test.go
relay_test.go
subscription_test.go
tag_test.go
utils_test.go

The `testify` was installed, but not used.

using testify instead of testing.T methods.

---

keyer/bunker.go
keyer/encrypted.go
keyer/lib.go
keyer/manual.go
keyer/plain.go
nip17/nip17.go

I need this to use Keyer interface.

error aware Keyer.GetPublicKey

---

count_test.go
event.go
kinds.go
sdk/tracker.go

ive added some mothods which were defined in my last pr but didn't get merged. also, kind3 is follow list.

feat(event): adding more helpers.

---

nip46/client.go

I don't know whether defer part is necessary.

bunker client connect: make context work

---

nip77/nip77.go

This pull request implements direction for synchronization using NIP77.

Implements Direction to NIP77

---

kinds.go
nip22/nip22.go
sdk/thread.go

I don't know if sdk/ is the best place to put the two functions.

Add NIP-22 support

---

nip11/nip11_test.go
nip11/types.go

add Retention to NIP-11
add `AddSupportedNIPs` method to `RelayInformationDocument`

fix: add retention to nip-11

---

nip86/methods.go

- implements https://github.com/nostr-protocol/nips/pull/1734

nip-86: update methods.

---

nip11/types.go
nip96/nip96_test.go
nipb0/blossom/download.go
sdk/kvstore/interface.go
sdk/kvstore/lmdb/store.go

- https://github.com/nostr-protocol/nips/pull/1821

feat(nip11): update to nips pr nostr-protocol/nip#1821
