nbd-wtf/go-nostr

relaypool.go, subscription.go
The `Sub()` function retrieves the list of filters from the
`Subscripton` object itself, and therefore it's unnecessary to pass it
in.  The argument is unused.
Here, we remove the function argument from the definition, and from the
single call site.  We then pass the filters to the initializer.
This makes it so that filters are in fact passed to the relay on the wire.
=> Remove unnecessary argument to subscription.Sub

connection.go, relaypool.go, subscription.go
We replace the bare websocket.Conn type with a new Connection type which
implements `WriteJSON`, `WriteMessage`, and `Close`.  The Connection
type adds mutexes around writes since gorilla doesn't support concurrent
writes to websockets.
Signed-off-by: Honza Pokorny <honza@pokorny.ca>
Might fix https://github.com/fiatjaf/noscl/issues/2
=> Add mutexes around websockets

nip04/nip04.go
Thought this might be useful since these functions are just boiler plate for most clients, so moving them into this lib could make sense. There is also a pull request for the `noscl` client that adds the following command:
```
noscl message [--reference=<id>...] <id> <content>
```
This uses the yet to be added nip04 package of this `go-nostr` module/library.
=> Adding nip04 (encrypted direct messages) support

go.mod, go.sum, relay.go, relay_test.go, relaypool.go
A websocket dial may hand for an unreasonably long time and a nostr client has no control over this when trying to connect to a relay.
Go started introducing context in networking since 2014 - see https://go.dev/blog/context - and by now many net functions have XxxContext equivalent, such as DialContext.
Example usage of the change introduced by this commit:
ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
defer cancel()
r, err := nostr.RelayConnectContext(ctx, "ws://relay.example.org")
The code above makes RelayConnectContext last at most 3 sec, returning an error if a connection cannot be established in the given time. This helps whenever a tight control over connection latency is required, such as distributed systems.
The change is backwards-compatible except the …
=> relay: introduce ConnectContext for better control over network latency

relay.go
I was getting some duplicate "REQ" ID's when using noscl publish. 
Tracked it down to math/rand usage instead of crypto/rand in relay.go
=> use crypto/rand instead of math/rand in relay.go for REQ <id>

relaypool.go
problem: panic if calling unsub more than once
It's a bit dangerous if calling unsub more than once causes a fatal panic.
=> problem: panic if calling unsub more than once

nip13/nip13.go, nip13/nip13_test.go
implementation as per NIP-13
https://github.com/nostr-protocol/nips/blob/e79c84ae/13.md
some benchmark results:
$ go test -bench . ./nip13
goos: linux
goarch: amd64
pkg: github.com/nbd-wtf/go-nostr/nip13
cpu: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
BenchmarkCheck-8                        144905385                8.328 ns/op
BenchmarkGenerateOneIteration-8           467874              2451 ns/op
BenchmarkGenerate/8bits-8                   4045           1033196 ns/op
BenchmarkGenerate/16bits-8                    16         101939954 ns/op
BenchmarkGenerate/24bits-8                     1        11411513764 ns/op
PASS
ok      github.com/nbd-wtf/go-nostr/nip13       22.220s
https://github.com/nbd-wtf/go-nostr/pull/6 is seemingly related but it refers to some other nip, in another repo. …
=> nip13: check and generate proof of work

relay.go, relay_test.go
the client never reported a failed status, for example when a relay responds with a:
["OK", event-id, false, "blocked"]
this was due to Relay.statusChans map missing a channel for an event when a nip-20 status command is reported by a relay. the reason this happened is due to the method's receiver, which was copied instead of referenced by a pointer:
func (r Relay) Publish(event Event) chan Status {
// uses a **copy** of statusChans here:
r.statusChans.Store(event.ID, statusChan)
...
}
the bugfix is a one character change:
func (r *Relay) Publish(event Event) chan Status
but while there, spotted another bug where an ok variable was shadowed and the status chan would've reported incorrect value:
// ok, which is a command status from earlier, is shadowed here:
if statusChan, ok := …
=> publish: correctly report failed command statuses from nip-20 relays

nip42/nip42.go
Trim the trailing slash when comparing the expected and found WS URLs to avoid conflicts.
Was considering also doing case insensitive, @fiatjaf what do you think? I can make a quick update to include that too.
=> trim trailing slash from expected and found relay URL, clean up

nip19/nip19_test.go
Minor change in `nip19/nip19_test.go`
=> Fix test nip19 variable naming

README.md, example/example.go, filter_test.go
1. Fix typo issue in README.md (GenerateKey -> GeneratePrivateKey);
2. Fix compiling issue in example.go;
3. Fix time comparison issue in filter_test.go, the time zone should be considered when do date/time compare.
=> Fix example compilation error

relay.go
- if `receivedEvent.ID` not match `event.ID`, may trigger an error `fatal error: sync: unlock of unlocked mutex`.
- if context canceled, it does not needs mutex.
=> Fix unblock mutex

nip42/nip42.go
Put signature verification as final step, as it is most expensive. Also check `event == nil` to prevent panics
=> Tweaked the NIP 42 Validation

filter.go, filter_aux.go
Adds `search` filter for nip50 support.
for: https://github.com/fiatjaf/relayer/pull/37
=> nip50: add filter.search field

relay.go, relay_test.go
Some relays require an origin header, so I added a passthrough. Maybe you want to merge this?
=> pass http headers to websocket conn

relay.go, relay_test.go
A race-condition exists between setting of the (unprotected) status and the callback which sets the status upon receiving an OK. The message is sent which can receive an OK in separate goroutine (setting status) prior to the status being set to 'sent.' The OK can be received prior to the status being set.
This fix also sets the status to PublishStatusFailed if the WriteJSON call fails.
=> Fix race condition on status in Relay.Publish method and failure to send

envelopes.go, envelopes_test.go
There is a chance the function can panic if a comma is included in the input which is invalid.
Fixes #92.
=> Fix panic in ParseMessage

pool.go
seenAlready is used to avoid duplicate events receiving at different times from multiple relays, but if left unchecked, memory will gradually be used; old events should be deleted after a certain period of time as they never arrive after EOSE is given.
=> seenAlready must drop older events

go.mod, pool.go
Sorry watching sub.EndOfStoredEvents in for loop make heavy loop if the chan is closed.
=> fix heavy loop

helpers.go
dgraph-io/ristretto use google/glog. glog rewrites flags on its own, which causes unexpected behaviour.
For example:
```go
package main
import (
"flag"
//_ "github.com/dgraph-io/ristretto/z"
)
func main() {
flag.Parse()
}
```
depend on dgraph-io/ristretto
```
$ ./test -h
Usage of ./test:
-alsologtostderr
log to standard error as well as files
-log_backtrace_at value
when logging hits line file:N, emit a stack trace
-log_dir string
If non-empty, write log files in this directory
-logtostderr
log to standard error instead of files
-stderrthreshold value
logs at or above this threshold go to stderr
-v value
log level for V logs
-vmodule value
comma-separated list of pattern=N settings for file-filtered logging
```
not depend on dgraph-io/ristretto
```
$ ./test -h
Usage of ./zz:
```
=> remove dependency for github.com/dgraph-io/ristretto/z

.github/workflows/test.yml
- update `actions/checkout` to v4 
- update `actions/setup-go` to v5 
To solve deprecation warnings in GitHub actions which were warning about old node 12 and node 16 action runtimes.
Also took the liberty of adding some whitespace between steps. Hopefully acceptable 😸
=> ci: update checkout and setup-go action versions

connection.go, relay.go
Currenlty it is missing and there is no way to connect to relay using custom CAs or to ignore TLS errors.
=> add option to connect with custom TLS

README.md, example/example.go
I was seeing this issue #100, I went to test it and it seems that the wss://nostr.zebedee.cloud relay is no longer available.
I switched to wss://relay.stoner.com and now it seems to be working fine.
=> changed nostr relays from examples

nip10/nip10.go
I'm not sure if this fix break something, I'm using it on njump to retrieve the parent of comments to an naddr1 event.
=> Support a tags in GetImmediateReply

normalize.go, normalize_test.go
Related: https://github.com/fiatjaf/nak/pull/22  
Without thinking much and doing things in a hurry, the commit above is wrong because `nak req` or `nak event` actually use under the hood the function `NormalizeURL`, and I thought they used the file `relay.go` in the [nak](https://github.com/fiatjaf/nak) repository.  
However, the commit above is not totally wrong, in a sense that the commit doesn't need to be removed, because it works with the `relay` flag. Image above.  
My bad.
=> Append 'ws://' prefix if url starts with localhost

nip46/dynamic-signer.go
Move out the `session.ParseRequest` call from the `else` branch. This caused an empty `Request` object to be used down in the function when the `Session` already existed.
=> nip46: fix HandleRequest request parsing logic

envelopes.go
Removes a duplicate array length check in the CountEnvelope Deserialization function
=> Removed duplicate array length check

sdk/feeds.go
Fix a nil pointer that occurs in FetchFeedPage when no data is returned from the KVStore.
Updates conditions on which to query locally to ensure it's only happening if the oldest timestamp in the KVStore for a pubkey is older than the upper bound of the time filter.
Locally reproduced with:
```go
package main
import (
"context"
"fmt"
"time"
"github.com/nbd-wtf/go-nostr"
"github.com/nbd-wtf/go-nostr/nip19"
"github.com/nbd-wtf/go-nostr/sdk"
)
func main() {
ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
defer cancel()
_, pubkey, err := nip19.Decode("npub180cvv07tjdrrgpa0j7j7tmnyl2yr6yr7l8j4s3evf6u64th6gkwsyjh6w6")
if err != nil {
panic("Unable to decode npub")
}
sys := sdk.NewSystem()
until := nostr.Now()
events, err := sys.FetchFeedPage(ctx, …
```
=> sdk/feeds: fix nil pointer error and conditional local query logic

event.go, event_test.go
Adding the lenght check of the Event.ID fixes issue #180
=> CheckID panics when event.ID has incorrect lenght.

nip42/nip42.go
When there is no relay tag, `ValidateAuthEvent` panics. To test it you can simply run
```golang
package main
import (
"fmt"
"github.com/nbd-wtf/go-nostr"
"github.com/nbd-wtf/go-nostr/nip42"
)
func main() {
auth := nostr.Event{
Kind: nostr.KindClientAuthentication,
Tags: nostr.Tags{{"challenge", "abc"}},
}
nip42.ValidateAuthEvent(&auth, "abc", "")
}
```
=> NIP-42 panic when there is no "relay" tag.

relay.go
I am running `go-nostr v0.49.7` and recently got multiple times this panic:
```
May 04 22:47:20 vertex crawler[13698]: panic: runtime error: invalid memory address or nil pointer dereference
May 04 22:47:20 vertex crawler[13698]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6c08d4]
May 04 22:47:20 vertex crawler[13698]: goroutine 2272862 [running]:
May 04 22:47:20 vertex crawler[13698]: github.com/nbd-wtf/go-nostr.(*Connection).WriteMessage(0x4002499f38?, {0xa9cbf0?, 0x4000164d20?}, {0x4000c89200?, 0x88d280?, 0x40013a8101?})
May 04 22:47:20 vertex crawler[13698]:         /home/admin/repos/working/go-nostr/connection.go:33 +0x24
May 04 22:47:20 vertex crawler[13698]: github.com/nbd-wtf/go-nostr.(*Relay).ConnectWithTLS.func2()
May 04 22:47:20 vertex crawler[13698]: …
```
=> Fix race in `ConnectWithTLS` where `relay.Connection` can be set to `nil` concurrently with writes, causing panics.
